package com.mogujie.tt.DB.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.mogujie.tt.DB.entity.UserEntity;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table ApplyUserInfo.
*/
public class ApplyUserDao extends AbstractDao<UserEntity, Long> {

    public static final String TABLENAME = "ApplyUserInfo";

    /**
     * Properties of entity UserEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PeerId = new Property(1, int.class, "peerId", false, "PEER_ID");
        public final static Property Gender = new Property(2, int.class, "gender", false, "GENDER");
        public final static Property MainName = new Property(3, String.class, "mainName", false, "MAIN_NAME");
        public final static Property PinyinName = new Property(4, String.class, "pinyinName", false, "PINYIN_NAME");
        public final static Property RealName = new Property(5, String.class, "realName", false, "REAL_NAME");
        public final static Property Avatar = new Property(6, String.class, "avatar", false, "AVATAR");
        public final static Property Phone = new Property(7, String.class, "phone", false, "PHONE");
        public final static Property Email = new Property(8, String.class, "email", false, "EMAIL");
        public final static Property DepartmentId = new Property(9, int.class, "departmentId", false, "DEPARTMENT_ID");
        public final static Property Status = new Property(10, int.class, "status", false, "STATUS");
        public final static Property Created = new Property(11, int.class, "created", false, "CREATED");
        public final static Property Updated = new Property(12, int.class, "updated", false, "UPDATED");
        public final static Property OpenId = new Property(13, String.class, "openid", false, "OPEN_ID");
        public final static Property ValidateType = new Property(14, int.class, "ValidateType", false, "VALIDATE_TYPE");
    };


    public ApplyUserDao(DaoConfig config) {
        super(config);
    }

    public ApplyUserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ApplyUserInfo' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'PEER_ID' INTEGER NOT NULL UNIQUE ," + // 1: peerId
                "'GENDER' INTEGER NOT NULL ," + // 2: gender
                "'MAIN_NAME' TEXT NOT NULL ," + // 3: mainName
                "'PINYIN_NAME' TEXT NOT NULL ," + // 4: pinyinName
                "'REAL_NAME' TEXT NOT NULL ," + // 5: realName
                "'AVATAR' TEXT NOT NULL ," + // 6: avatar
                "'PHONE' TEXT NOT NULL ," + // 7: phone
                "'EMAIL' TEXT NOT NULL ," + // 8: email
                "'DEPARTMENT_ID' INTEGER NOT NULL ," + // 9: departmentId
                "'STATUS' INTEGER NOT NULL ," + // 10: status
                "'CREATED' INTEGER NOT NULL ," + // 11: created
                "'UPDATED' INTEGER NOT NULL ," +// 12: updated
                "'OPEN_ID' TEXT NOT NULL ," +
                "'VALIDATE_TYPE' INTEGER NOT NULL);");
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_ApplyUserInfo_PEER_ID ON ApplyUserInfo" +
                " (PEER_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ApplyUserInfo'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getPeerId());
        stmt.bindLong(3, entity.getGender());
        stmt.bindString(4, entity.getMainName());
        stmt.bindString(5, entity.getPinyinName());
        stmt.bindString(6, entity.getRealName());
        stmt.bindString(7, entity.getAvatar());
        stmt.bindString(8, entity.getPhone());
        stmt.bindString(9, entity.getEmail());
        stmt.bindLong(10, entity.getDepartmentId());
        stmt.bindLong(11, entity.getStatus());
        stmt.bindLong(12, entity.getCreated());
        stmt.bindLong(13, entity.getUpdated());
        stmt.bindString(14, entity.getOpenid());
        stmt.bindLong(15, entity.getValidateType());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UserEntity readEntity(Cursor cursor, int offset) {
        UserEntity entity = new UserEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // peerId
            cursor.getInt(offset + 2), // gender
            cursor.getString(offset + 3), // mainName
            cursor.getString(offset + 4), // pinyinName
            cursor.getString(offset + 5), // realName
            cursor.getString(offset + 6), // avatar
            cursor.getString(offset + 7), // phone
            cursor.getString(offset + 8), // email
            cursor.getInt(offset + 9), // departmentId
            cursor.getInt(offset + 10), // status
            cursor.getInt(offset + 11), // created
            cursor.getInt(offset + 12), // updated
            cursor.getString(offset + 13), // updated
            cursor.getInt(offset + 14) // updated

        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPeerId(cursor.getInt(offset + 1));
        entity.setGender(cursor.getInt(offset + 2));
        entity.setMainName(cursor.getString(offset + 3));
        entity.setPinyinName(cursor.getString(offset + 4));
        entity.setRealName(cursor.getString(offset + 5));
        entity.setAvatar(cursor.getString(offset + 6));
        entity.setPhone(cursor.getString(offset + 7));
        entity.setEmail(cursor.getString(offset + 8));
        entity.setDepartmentId(cursor.getInt(offset + 9));
        entity.setStatus(cursor.getInt(offset + 10));
        entity.setCreated(cursor.getInt(offset + 11));
        entity.setUpdated(cursor.getInt(offset + 12));
        entity.setOpenid(cursor.getString(offset + 13));
        entity.setValidateType(cursor.getInt(offset + 14));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(UserEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(UserEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
